### ISSUE TITLE
Migrate from Eel to an alternative Python - JavaScript linker

### ISSUE THREAD

**Issue by JaimePSantos** [JaimePSantos/QWAK#100]
## Enhancement proposal

Eel appears to have been [abandoned](https://github.com/ChrisKnott/Eel/issues/600). This means that we should probably migrate the GUI to a better supported JavaScript link before something breaks.

**Comment by shirooo39** [comment]
> ## Enhancement proposal
> 
> Eel appears to have been [abandoned](https://github.com/ChrisKnott/Eel/issues/600). This means that we should probably migrate the GUI to a better supported JavaScript link before something breaks.
> ## Additional comments

I just found out about eel and I think this is a really good project.
too bad that it's been semi-abandoned by the author.

so, what good alternatives we for option?

**Comment by JaimePSantos** [comment]
Yeah it's very unfortunate its no longer being developed.

Im currently looking into alternatives. Maybe flask or electron, but im not too familiar with either of those yet.

Hopefully flask will be a good fit, but im not sure how much of the project would have to be rewritten to make this change.

**Comment by shirooo39** [comment]
> Yeah it's very unfortunate its no longer being developed.
> 
> Im currently looking into alternatives. Maybe flask or electron, but im not too familiar with either of those yet.
> 
> Hopefully flask will be a good fit, but im not sure how much of the project would have to be rewritten to make this change.

I want to learn more about GUI programming in Python.
I've tried PySide6 a year ago. my code was a mess, but at least the end result worked.

I'm looking for a simpler approach, hence why I just want to design the UI with HTML, CSS, and JS.
all I need is to have the app in a standalone window and no need to have Chrome installed.

I'm not sure how this is possible, but probably by using a built-in webview or an embedded one?
anyway, eel was amazing. the ability that allows JS and Python communicate together is amazing (even though I've not tried it yet). if there's an alternative with the same functionallity that allows communication in both-world AND if possible, support for templating language like Jinja or Nunjucks (no Liquid, it sucks) that'd be amazing.

**Comment by JaimePSantos** [comment]
> > Yeah it's very unfortunate its no longer being developed.
> > Im currently looking into alternatives. Maybe flask or electron, but im not too familiar with either of those yet.
> > Hopefully flask will be a good fit, but im not sure how much of the project would have to be rewritten to make this change.
> 
> I want to learn more about GUI programming in Python. I've tried PySide6 a year ago. my code was a mess, but at least the end result worked.
> 
> I'm looking for a simpler approach, hence why I just want to design the UI with HTML, CSS, and JS. all I need is to have the app in a standalone window and no need to have Chrome installed.
> 
> I'm not sure how this is possible, but probably by using a built-in webview or an embedded one? anyway, eel was amazing. the ability that allows JS and Python communicate together is amazing (even though I've not tried it yet). if there's an alternative with the same functionallity that allows communication in both-world AND if possible, support for templating language like Jinja or Nunjucks (no Liquid, it sucks) that'd be amazing.

Hey i've been sinking some time into this and it seems you can use flask and ajax to achieve similar results to eel, although a few extra steps are required. I've got some of the functionality running in [179cb9f](https://github.com/JaimePSantos/QWAK/commit/179cb9fac7ef2b22b34c13cf554930baecd9a4ef) if you wanna check it out.

**Comment by JaimePSantos** [comment]
This was completed in #166
