### ISSUE TITLE
Create contribution tutorial in documentation.

### ISSUE THREAD

**Issue by JaimePSantos** [JaimePSantos/QWAK#115]
## Enhancement proposal

Move the contributing to the package part of the readme to its own documentation page.

**Comment by lazyturd** [comment]
Hello, i'm new to the open source space and i was wondering if i could be assigned to solve this issue. Thanks

**Comment by JaimePSantos** [comment]
Hi! Sure thing, it should be as simple as creating a contribution.rst file, moving the contribution text from the readme to that page in the correct format (you can check the installation.rst to get a feel for this) and then including the file in the index.rst toctree. 

Right now you should do this on the documentation folder, and when you've made your changes run `make github` or `make linuxgit` inside the documentation folder to move those files. Any questions just let me know!
